name: turbo-docker-monorepo-dev
x-defaults:
  &defaults
  init: true
  tty: true
  stdin_open: true
  networks:
    - monorepo_network

services:

  ####################################################################

  api:
    <<: *defaults
    ports:
      - "3200:3200"
    command: yarn workspace api start:dev
    environment:
      - PORT=3200
      - IN_CONTAINER=1
    build:
      args:
        APP: api
        START_COMMAND: start:dev
      context: .
      dockerfile: ./dockerfiles/Dockerfile.dev
    volumes:
      - ./apps/api:/app/apps/api
      - /app/apps/api/node_modules

####################################################################        

networks:
  monorepo_network:
